# Generated by Django 4.1.7 on 2023-03-06 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='blurb',
        ),
    ]
